### ISSUE TITLE
Website To-Do List

### ISSUE THREAD

**Issue by rpaladin** [UPBGE/upbge.github.io#8]
### Comments

I create this issue to help & remind website developers.
Feel free to manually edit this post if a task has been completed or post ideas or requests if you have any.

### Work-in-Progress'

- [x] ~Add basic `community` page content.~
- [x] Add `Legacy 0.2` download links as promised for the download page.
- [ ] Add Linux `AArch64` support as promised at the download page.
- [ ] Add better mobile response content for the website, especially for the `download` page.
- [ ] Button components don't have margin or padding detection.
- [ ] Implement real `404` error page instead of redirecting to home page.

### Current Bugs

- [x] ~https://upbge.org when linked doesn't show a `preview image`.~
- [x] [CRITICAL] Documentation `search results` don't automatically refresh the current page to show new content.
NOTE_1: this only happens for the 0.3 API but works for the 0.3 Manual & UPBGE 0.2.x Manual/API.
NOTE_2: this only happens with the website Sphinx, not old Sphinx.
https://upbge.org/docs/latest/api/index.html works fine but not https://upbge.org/#/documentation/docs/latest/api/index.html
- [ ] Navigation header isn't affected by light/dark color theme toggles.
- [ ] `scrollTo` top doesn't always work when switching to `Documentation`, `Community`, or `Download` page.

**Comment by rpaladin** [comment]
Added navigation header bug about themes.

**Comment by rpaladin** [comment]
Migrating to: https://github.com/UPBGE/upbge.github.io/projects/1
